"""add_edi_transaction_log

Revision ID: ec78d2c05126
Revises: 001
Create Date: 2026-02-10 16:12:36.909820
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers
revision: str = "ec78d2c05126"
down_revision: str | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edi_transaction_log",
        sa.Column("log_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.Column("document_type", sa.String(length=10), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("trading_partner_id", sa.String(length=100), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("parsed_records", sa.Integer(), nullable=True),
        sa.Column("errors", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("direction IN ('inbound', 'outbound')", name="ck_edi_direction"),
        sa.CheckConstraint("document_type IN ('846', '856', '810', '850', '997')", name="ck_edi_document_type"),
        sa.CheckConstraint(
            "status IN ('received', 'parsing', 'processed', 'failed', 'acknowledged')", name="ck_edi_status"
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integrations.integration_id"],
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_index("ix_edi_log_customer", "edi_transaction_log", ["customer_id"], unique=False)
    op.create_index(
        "ix_edi_log_customer_type", "edi_transaction_log", ["customer_id", "document_type", "created_at"], unique=False
    )
    op.create_index("ix_edi_log_integration", "edi_transaction_log", ["integration_id"], unique=False)
    # NOTE: inventory_levels_timestamp_idx and transactions_timestamp_idx are
    # TimescaleDB-managed hypertable indexes — do NOT drop them via Alembic.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_edi_log_integration", table_name="edi_transaction_log")
    op.drop_index("ix_edi_log_customer_type", table_name="edi_transaction_log")
    op.drop_index("ix_edi_log_customer", table_name="edi_transaction_log")
    op.drop_table("edi_transaction_log")
    # ### end Alembic commands ###
